apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: demo
  namespace: managed-rbean
spec:
  application: appstudio
  environment: production
  origin:
    namespace: ralphjbean
  releaseStrategy: m7-strategy
