apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: hacbsreleaseservice
spec:
  componentName: hacbsreleaseservice
  application: appstudio
  source:
    git:
      url: https://github.com/redhat-appstudio/release-service
      dockerfileUrl: https://github.com/redhat-appstudio/release-service/blob/main/Dockerfile
