apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/scoheb/fbc-index-testing:latest
  displayName: My Operator Catalog
  publisher: grpc
