apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-operator
  namespace: my-namespace
spec:
  channel: stable
  name: kubevirt-hyperconverged
  source: my-operator-catalog
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
  startingCSV: kubevirt-hyperconverged-operator.v4.10.2