---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-pvc
  namespace: managed-release-team-tenant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
