apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: mvp-policy
  namespace: managed-release-team
spec:
  description: Red Hat's enterprise requirements
  exceptions:
    nonBlocking:
    - not_useful
    - attestation_task_bundle
    - java
    - tasks
    - test
  sources:
    - data:
        - "git::https://github.com/hacbs-contract/ec-policies.git//data"
      name: ec-policies
      policy:
        - "git::https://github.com/hacbs-contract/ec-policies.git//policy"
