apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: mvp-policy
  namespace: managed-release-team
spec:
  description: Red Hat's enterprise requirements
  exceptions:
    nonBlocking:
    - attestation_task_bundle
    - java
    - tasks
    - test
    - hermetic_build_task.build_task_not_hermetic
    - buildah_build_task.dockerfile_param_external_source
  publicKey: |-
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEODgxyIz09vBqJlXXzjp/X2h17WIt
    jCVQhnDYVWHvXhw6rgqGeg6NTUxIEhRQqQZaF9mcBotHkuYGJfYZbai+FA==
    -----END PUBLIC KEY-----
  sources:
    - data:
        - "git::https://github.com/hacbs-contract/ec-policies.git//data"
      name: ec-policies
      policy:
        - "git::https://github.com/hacbs-contract/ec-policies.git//policy"
