apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: mvp-policy
  namespace: managed-release-team-tenant
spec:
  description: Red Hat's enterprise requirements
  exceptions:
    nonBlocking:
    - attestation_task_bundle
    - java
    - tasks
    - test
    - hermetic_build_task.build_task_not_hermetic
    - buildah_build_task.dockerfile_param_external_source
    - step_image_registries.disallowed_task_step_image
  publicKey: |-
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1D2S9GEhb0op0ZVv/53lxnLUYjP3
    jG0/VJFmmggPoGNmg1GagPw8dfpq2qTad5MV/JnPFVCar3pBv/55RO8abg==
    -----END PUBLIC KEY-----
  sources:
    - data:
        - "git::https://github.com/hacbs-contract/ec-policies.git//data"
      name: ec-policies
      policy:
        - "git::https://github.com/hacbs-contract/ec-policies.git//policy"
