apiVersion: appstudio.redhat.com/v1alpha1
kind: Environment
metadata:
  name: production
  namespace: managed-release-team
spec:
  deploymentStrategy: Manual
  displayName: demo production
  type: POC
