apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: sre-production
  namespace: managed-rbean
spec:
  application: demo-app
  environment: production
  origin:
    namespace: ralphjbean
  releaseStrategy: m7-strategy
