kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: managed-rbean
 name: role-m7-service-account
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: role-m7-service-account-binding
 namespace: managed-rbean
subjects:
- kind: ServiceAccount
  name: m7-service-account
  namespace: managed-rbean
roleRef:
 kind: Role
 name: role-m7-service-account
 apiGroup: rbac.authorization.k8s.io
