apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: demo-app-7kzkm-demo-release
  namespace: ralphjbean
spec:
  applicationSnapshot: demo-app-7kzkm
  releasePlan: sre-production
